"""Static English skeletons for a Singapore façade Contractor's Proposal draft.

Filled by sg_facade.build_sg_facade_bidbook. No invented prices or certificates.
"""

WATERMARK = (
    "DRAFT · {legal_name} ({tag}) · Not for GeBIZ submission · "
    "NOT FOR award or stamping"
)

FORM_OF_TENDER = """## 1. Cover & Form of Tender

**Tenderer (demo SME):** {legal_name}
**Registered address:** {address}
**UEN:** {uen}
**BCA workhead / financial grade:** {workhead}

The Tenderer offers to design, supply, deliver and install the façade / curtain-wall
works described in the Employer's Requirements, in accordance with the Public Sector
Standard Conditions of Contract (PSSCOC) where applicable, and the Instructions to
Tenderers.

| Item | Offer |
|------|--------|
| Project | {project_title} |
| Contract sum (SGD) | S$ [TO FILL] |
| Tender validity | [TO FILL] calendar days |
| Authorised signatory | [TO FILL] |
| Date | [TO FILL] |

This Form of Tender is a **draft assembly**. It is **NOT FOR** submission on GeBIZ
until a director completes every `[TO FILL]` field and signs.
"""

EXEC_SUMMARY = """## 2. Executive Summary

{legal_name} (demo profile only) submits this **draft** Contractor's Proposal for
**{project_title}**, a Singapore curtain-wall / building-envelope package.

- **Scope in this draft:** requirement capture, compliance / deviation schedule,
  technical method, programme, and **tool-verified packing / shipping evidence**.
- **Requirements extracted:** {n_req} · **covered by delivery tools:** {n_covered} ·
  **readiness:** {readiness}
- **Items still requiring SME / legal / commercial sign-off:** {n_open}

We do **not** invent track record, BCA grades, test-report numbers or prices.
Those remain `[TO FILL]`.
"""

TECHNICAL = """## 4. Technical Approach (Singapore façade)

The proposed envelope will be developed as unitised and/or stick curtain wall,
aluminium cladding and vision/spandrel glazing, coordinated with the Architect
and QP. Design and performance will follow, as applicable:

- **SS 654:2020** Code of practice for curtain walls (supersedes SS 381 / CP 96)
- BCA **Green Mark 2021** energy and envelope intent (U-value / SHGC to Employer's
  specifications — values `[TO FILL]` after design)
- Relevant Singapore Standards for glass, aluminium and sealants
- Periodic façade inspection awareness under the Building Control (Periodic
  Inspection of Buildings) regime

**Systems (indicative — confirm against drawings):**

| System | Intent | Evidence status |
|--------|--------|-----------------|
| Unitised / stick CW | Shop drawings + structural calcs | [TO FILL] PE endorsement |
| IGU / laminated glass | Spec vs wind / impact | [TO FILL] test reports |
| Aluminium frames | Alloy / finish / thermal break | [TO FILL] mill certs |
| Anchors / brackets | To structure as designed | [TO FILL] |

No laboratory report numbers are generated by this draft.
"""

METHOD = """## 5. Method Statement & Programme

Indicative sequence (Singapore site; dates `[TO FILL]`):

1. Design development, PE check, material submittals
2. Factory fabrication and QA (crates / steel frames as specified)
3. Export packing and ocean freight (see Chapter 6 — tool evidence)
4. Discharge, customs, delivery to site / staging yard
5. Tower-crane / MHU installation, sealing, cleaning, snagging
6. As-built, warranties, O&M

{schedule_block}
"""

WSH = """## 7. WSH, Quality & Environment

- Workplace Safety and Health Act and subsidiary regulations; site WSH plan `[TO FILL]`
- **bizSAFE** level: `[TO FILL]` (certificate number not invented)
- Quality: ITP for fabrication, glass, waterproofing and installation `[TO FILL]`
- Environment: packaging protection, waste segregation, Green Mark product data `[TO FILL]`
- Insurance / VGM / shipping documents: commercial owner (see Annex B)

This chapter is a compliance reminder, not a stamped WSH or ISO certificate.
"""

RESOURCES = """## 8. Resources, Track Record & Commercial

### 8.1 Organisation

| Role | Name | PE / registration |
|------|------|-------------------|
| Project manager | [TO FILL] | [TO FILL] |
| Design PE (façade) | [TO FILL] | [TO FILL] |
| Site supervisor | [TO FILL] | [TO FILL] |

### 8.2 Similar Singapore / regional projects

| Project | Year | Scope | Value (SGD) | Client |
|---------|------|-------|-------------|--------|
| [TO FILL] | [TO FILL] | [TO FILL] | S$ [TO FILL] | [TO FILL] |
| [TO FILL] | [TO FILL] | [TO FILL] | S$ [TO FILL] | [TO FILL] |

**UEN, BCA workhead and financial grade remain `[TO FILL]`. No fabricated awards.**

### 8.3 Schedule of prices (not priced)

| Item | Description | Qty | Unit | Rate (SGD) | Amount (SGD) |
|------|-------------|-----|------|------------|--------------|
| 1 | Design & shop drawings | [TO FILL] | lot | S$ [TO FILL] | S$ [TO FILL] |
| 2 | Supply of curtain wall | [TO FILL] | m² | S$ [TO FILL] | S$ [TO FILL] |
| 3 | Installation & sealing | [TO FILL] | m² | S$ [TO FILL] | S$ [TO FILL] |
| 4 | Ocean freight & packing | [TO FILL] | lot | S$ [TO FILL] | S$ [TO FILL] |
| | **Tender sum** | | | | S$ [TO FILL] |

Commercial figures are intentionally blank. Filling them is a human pricing act.
"""
