#!/usr/bin/env python3
"""ux(round2): 从 workbench/seed.json 生成 66 岗 @补全静态数据（零 CDN，本地常量）。

产物两份，同一生成源，避免漂移：
1. demo/static/posts.js      —— :8765 Rust 工作台 <script> 兜底加载（window.CB_POSTS）
2. frontend/workbench.html   —— :8000 大 Team 台内嵌 CB_POSTS BEGIN/END 标记块（离线兜底，
                                运行时仍优先拉同源 /api/experts）
运行时数据优先级：本地 /api（catalog/experts）→ window.CB_POSTS。
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
seed = json.loads((ROOT / "workbench" / "seed.json").read_text(encoding="utf-8"))
experts = [
    {
        "id": e["id"],
        "name": e["name"],
        "aliases": list(e.get("aliases") or []),
        "category": e.get("category", ""),
        "category_name": e.get("category_name", ""),
    }
    for e in seed["experts"]
]
assert len(experts) == 66, f"expect 66 posts from seed.json, got {len(experts)}"

begin = "/* === CB_POSTS BEGIN · 由 scripts/gen_cb_posts.py 生成自 workbench/seed.json，勿手改 === */"
end = "/* === CB_POSTS END === */"
body = "window.CB_POSTS = " + json.dumps(experts, ensure_ascii=False, separators=(",", ":")) + ";"
block = begin + "\n" + body + "\n" + end

# 1) demo/static/posts.js（:8765 兜底数据）
posts_js = (
    "/* Generated by scripts/gen_cb_posts.py from workbench/seed.json — 66 岗 @补全数据，零 CDN。 */\n"
    + block
    + "\n"
)
(ROOT / "demo" / "static" / "posts.js").write_text(posts_js, encoding="utf-8")

# 2) frontend/workbench.html 内嵌块（有标记则原位更新，无标记则插在 new Vue( 之前）
wb_path = ROOT / "frontend" / "workbench.html"
text = wb_path.read_text(encoding="utf-8")
pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
if pat.search(text):
    text = pat.sub(lambda m: block, text, count=1)
else:
    marker = "    new Vue({"
    assert text.count(marker) == 1, "workbench.html: expect exactly one 'new Vue({'"
    text = text.replace(marker, block + "\n" + marker, 1)
wb_path.write_text(text, encoding="utf-8")

print(f"CB_POSTS: {len(experts)} posts -> demo/static/posts.js + frontend/workbench.html (embedded)")
