#!/usr/bin/env python3
"""ux(round9): 生成 test/sim_materials 票清单静态数据（零 CDN，本地常量）。

gen_cb_posts.py 同款模式：一份生成源，两份产物，避免漂移：
1. demo/static/tickets.js    —— :8765 Rust 工作台 <script> 兜底加载（window.CB_TICKETS）
2. frontend/workbench.html   —— :8000 大 Team 台内嵌 CB_TICKETS BEGIN/END 标记块

数据源：test/sim_materials/*/materials.xlsx（磁盘枚举，文件必须真实存在）
      + test/sim_materials/INDEX.json（story/n_lines/net_kg 元数据，缺省留空不编）。
两端 /pack 命令面板的「票选择子菜单」消费这份清单——与磁盘一致由本脚本断言。
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SIM = ROOT / "test" / "sim_materials"

index = {}
if (SIM / "INDEX.json").is_file():
    index = json.loads((SIM / "INDEX.json").read_text(encoding="utf-8")).get("cases", {})

tickets = []
for d in sorted(SIM.iterdir()):
    if not d.is_dir() or d.name.startswith("."):
        continue
    xlsx = d / "materials.xlsx"
    if not xlsx.is_file():
        continue
    meta = index.get(d.name, {})
    rel = xlsx.relative_to(ROOT).as_posix()
    tickets.append(
        {
            "id": d.name,
            "xlsx": rel,
            "story": str(meta.get("story") or ""),
            "n_lines": meta.get("n_lines") if isinstance(meta.get("n_lines"), int) else None,
            "net_kg": meta.get("net_kg") if isinstance(meta.get("net_kg"), (int, float)) else None,
        }
    )
assert tickets, "no sim_materials tickets found under test/sim_materials"

begin = "/* === CB_TICKETS BEGIN · 由 scripts/gen_cb_tickets.py 生成自 test/sim_materials，勿手改 === */"
end = "/* === CB_TICKETS END === */"
body = "window.CB_TICKETS = " + json.dumps(tickets, ensure_ascii=False, separators=(",", ":")) + ";"
block = begin + "\n" + body + "\n" + end

# 1) demo/static/tickets.js（:8765 兜底数据）
(ROOT / "demo" / "static" / "tickets.js").write_text(
    "/* Generated by scripts/gen_cb_tickets.py from test/sim_materials — /pack 票清单，零 CDN。 */\n"
    + block
    + "\n",
    encoding="utf-8",
)

# 2) frontend/workbench.html 内嵌块（有标记则原位更新，无标记则插在 CB_POSTS 块之前）
wb_path = ROOT / "frontend" / "workbench.html"
text = wb_path.read_text(encoding="utf-8")
pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
if pat.search(text):
    text = pat.sub(lambda m: block, text, count=1)
else:
    marker = "/* === CB_POSTS BEGIN"
    assert text.count(marker) == 1, "workbench.html: expect exactly one CB_POSTS BEGIN marker"
    text = text.replace(marker, block + "\n" + marker, 1)
wb_path.write_text(text, encoding="utf-8")

print(f"CB_TICKETS: {len(tickets)} tickets -> demo/static/tickets.js + frontend/workbench.html (embedded)")
