#!/usr/bin/env node
// Real UI handlers with an offline HTTP boundary; no OCR/model/solver success claims.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../demo/static/logistics.html'),'utf8');
const source=fs.readFileSync(path.join(__dirname,'../demo/static/logistics.js'),'utf8');
const modulePromise=import('data:text/javascript;base64,'+Buffer.from(source+'\n//# sourceURL=logistics-ui-under-test.mjs').toString('base64'));
const copy=v=>JSON.parse(JSON.stringify(v));
const response=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const SIGNOFF='我明白，将由持证人员签认',PID='a'.repeat(32),OTHER='b'.repeat(32),DID='c'.repeat(32),PROPOSAL='d'.repeat(32);
function ledger(){return {schema:'civil.logistics.v1',source:{filename:'teaching.xlsx',sha256:'e'.repeat(64),bytes:100},extraction:{engine:'openpyxl',synthetic:true},rows:[{id:'R00001',package_id:'BOX-1',material_id:'MAT-1',name:'演示物料',spec:'UNSPECIFIED',package_count:1,quantity:10,units_per_package:10,unit:'PCS',length_mm:1000,width_mm:800,height_mm:600,dimension_scope:'package',net_kg:100,gross_kg:120,weight_scope:'package',evidence:{quantity:{raw:'10 PCS',header:'数量',source:{sheet:'装箱单',row:5,column:3}}}}],totals:[]};}
const audit={ok:true,issues:[],counts:{rows:1,errors:0,warnings:0}};
function project(revision=1,extra={}){return {id:PID,name:'合成台账',revision,document:ledger(),audit:copy(audit),summary:{totals:{package_count:1,quantity:10,net_kg:100,gross_kg:120},quantities_by_unit:{PCS:10}},confirmed:false,versions:revision>1?[{revision:revision-1,updated_at:'2026-09-21'}]:[],can_undo:revision>1,...extra};}
function draft(){return {document_id:DID,document:ledger(),audit:copy(audit),summary:project().summary,synthetic:true,source_url:'https://untrusted.invalid/source'};}
function proposal(extra={}){return {proposal_id:PROPOSAL,project:{id:PID,revision:1},action:null,changes:[{row_id:'R00001',field:'quantity',before:10,after:12}],proposal:{source_text:'用户明确修订',changes:[{row_id:'R00001',field:'quantity',before:10,after:12}]},...extra};}
const pack=(extra={})=>({ok:true,revision:1,mode:'packaged',result:{ok:true,can_fit:true,containers_used:1,n_boxes:1,container_type:'20GP'},...extra});
class Node {
  constructor(tag,doc){this.tagName=tag;this.doc=doc;this.children=[];this.listeners={};this.style={};this.dataset={};this.attributes={};this.value='';this.checked=false;this.disabled=false;this.hidden=false;this.textContent='';this.files=[];doc.nodes.push(this);}
  append(...children){this.children.push(...children);}replaceChildren(...children){this.children=[...children];}
  setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k];}
  addEventListener(name,fn){(this.listeners[name]||=[]).push(fn);}remove(){}scrollIntoView(){}
  async emit(name,other={}){const event={target:this,preventDefault(){},...other};await Promise.all((this.listeners[name]||[]).map(fn=>fn(event)));}
  async click(){if(!this.disabled)await this.emit('click');}
}
function dom(){const doc={nodes:[],ids:{},cookie:'',createElement(tag){return new Node(tag,this);},getElementById(id){assert.ok(this.ids[id],`missing UI element ${id}`);return this.ids[id];},querySelectorAll(selector){if(selector==='[data-ledger-field]')return this.nodes.filter(n=>n.dataset.ledgerField);assert.equal(selector,'main button,main input,main select,main textarea');return this.nodes.filter(n=>['button','input','select','textarea'].includes(n.tagName));}};
  for(const match of html.matchAll(/<([a-z][a-z0-9]*)\b([^>]*?)>/g)){const id=/\bid="([^"]+)"/.exec(match[2]);if(id){doc.ids[id[1]]=doc.createElement(match[1]);doc.ids[id[1]].hidden=/\bhidden\b/.test(match[2]);}}
  doc.body=doc.createElement('body');doc.ids.packingMode.value='packaged';doc.ids.containerType.value='20GP';doc.ids.maxContainers.value='1';doc.ids.exportFormat.value='xlsx';return doc;
}
async function app(fetcher=async()=>response({projects:[]}),{saved=true,...options}={}){const doc=dom(),downloads=[],win={location:{search:''},history:{replaceState(){}},addEventListener(){}};const {startLogisticsApp}=await modulePromise;const instance=startLogisticsApp(doc,{initialize:false,fetch:fetcher,window:win,download:(blob,name)=>downloads.push({blob,name}),...options});if(saved)instance.acceptProject(project());return {instance,doc,downloads,win};}
const text=node=>node.textContent+' '+node.children.map(text).join(' ');
const field=(doc,row,field)=>doc.nodes.filter(node=>node.dataset.rowId===row && node.dataset.ledgerField===field).at(-1);

test('unknown values stay unknown; explicit positive finite numbers, count integers and field whitelist are enforced',async()=>{const {displayValue,parseEdit}=await modulePromise;assert.equal(displayValue('UNSPECIFIED'),'待确认');assert.equal(parseEdit('gross_kg',''),'UNSPECIFIED');assert.equal(parseEdit('quantity','12'),12);assert.equal(parseEdit('net_kg','0.5'),.5);for(const value of ['NaN','Infinity','-1','0','1e3','2.5','true'])assert.throws(()=>parseEdit('quantity',value));assert.throws(()=>parseEdit('__proto__','1'));assert.throws(()=>parseEdit('dimension_scope','row'));assert.equal(parseEdit('weight_scope','row'),'row');});
test('draft parsing is not a saved project and cannot edit, confirm, chat or compute',async()=>{let calls=0;const {instance,doc}=await app(async()=>{calls++;return response({});},{saved:false});instance.acceptDraft(draft());instance.edit('R00001','quantity','12');await instance.calculate();await instance.chat('汇总箱单');assert.equal(calls,0);assert.equal(instance.state.pending.size,0);assert.equal(doc.ids.confirmLedger.disabled,true);assert.equal(doc.ids.calculate.disabled,true);assert.equal(doc.ids.saveProject.disabled,false);assert.equal(doc.ids.sourceDownload.href,`/api/logistics/documents/${DID}/source`);});
test('typing edits never changes saved values or summary; application requires an explicit diff confirmation',async()=>{const requests=[];const {instance,doc}=await app(async(url,init)=>{requests.push({url,body:init.body?JSON.parse(init.body):null});if(url.endsWith('/propose'))return response(proposal());if(url.endsWith('/apply')){const p=project(2);p.document.rows[0].quantity=12;return response({project:p});}return response({projects:[]});});const input=field(doc,'R00001','quantity');input.value='12';await input.emit('input');assert.equal(instance.state.project.document.rows[0].quantity,10);assert.equal(instance.state.project.summary.totals.quantity,10);await instance.reviewEdits();assert.match(text(doc.ids.proposalRows),/10.*12/);await instance.applyProposal();assert.equal(requests.length,1);doc.ids.confirmProposal.checked=true;await doc.ids.confirmProposal.emit('change');await doc.ids.applyProposal.click();assert.equal(instance.state.project.revision,2);assert.equal(instance.state.project.document.rows[0].quantity,12);assert.equal(instance.state.pending.size,0);assert.equal(instance.state.project.confirmed,false);assert.deepEqual(requests[0].body.changes,[{row_id:'R00001',field:'quantity',value:12}]);});
test('a further edit invalidates an already-reviewed proposal and clears its confirmation',async()=>{const {instance,doc}=await app(async()=>response(proposal()));instance.edit('R00001','quantity','12');await instance.reviewEdits();doc.ids.confirmProposal.checked=true;instance.edit('R00001','quantity','13');assert.equal(instance.state.proposal,null);assert.equal(doc.ids.confirmProposal.checked,false);assert.equal(doc.ids.applyProposal.disabled,true);assert.equal(instance.state.pending.size,1);});
test('invalid pending inputs block proposal, calculation, export and project switching without losing the input',async()=>{let calls=0;const {instance,doc}=await app(async()=>{calls++;return response({});});instance.edit('R00001','quantity','oops');await instance.reviewEdits();doc.ids.confirmation.value=SIGNOFF;await instance.calculate();await instance.exportProject();await instance.openProject(OTHER);assert.equal(calls,0);assert.equal(instance.state.pending.get('R00001:quantity').raw,'oops');instance.discardEdits();assert.equal(instance.state.pending.size,0);assert.equal(instance.state.project.document.rows[0].quantity,10);});
test('save binds the cached original and disables cancellation throughout durable writing',async()=>{const slow=deferred();let body,calls=0;const {instance,doc}=await app(async(url,init)=>{calls++;if(url.endsWith('/projects') && init.method==='POST'){body=JSON.parse(init.body);return slow.promise;}return response({projects:[]});},{saved:false});instance.acceptDraft(draft());doc.ids.projectName.value='学校比赛台账';const saving=instance.save();assert.equal(instance.state.busy.write,true);assert.equal(doc.ids.cancel.hidden,true);await instance.cancel();assert.equal(instance.state.busy.write,true);slow.resolve(response({project:project()}));await saving;assert.deepEqual(body,{document_id:DID,name:'学校比赛台账'});assert.equal(instance.state.project.id,PID);assert.equal(instance.state.draft,null);assert.equal(doc.ids.sampleBadge.hidden,false);assert.match(doc.ids.agentLink.href,new RegExp(PID));assert.ok(calls>=1);});
test('late project read cannot replace a newer project read',async()=>{const old=deferred();const {instance}=await app(url=>url===`/api/logistics/projects/${PID}`?old.promise:Promise.resolve(response(url.includes('/cancel')?{ok:true}:{project:project(3,{id:OTHER,name:'最新选择'})})));const loading=instance.openProject(PID);await instance.openProject(OTHER);old.resolve(response({project:project()}));await loading;assert.equal(instance.state.project.id,OTHER);assert.equal(instance.state.project.revision,3);});
test('cancelled upload/example response cannot erase a saved project',async()=>{const old=deferred();const {instance}=await app(url=>url.endsWith('/example')?old.promise:Promise.resolve(response({ok:true})));const loading=instance.example();await instance.cancel();old.resolve(response(draft()));await loading;assert.equal(instance.state.project.id,PID);assert.equal(instance.state.draft,null);assert.equal(instance.state.busy,null);});
test('409 application conflict preserves draft fields, proposal and original revision for review',async()=>{const {instance,doc}=await app(async url=>url.endsWith('/propose')?response(proposal()):response({detail:'台账已改变'},409));instance.edit('R00001','quantity','12');await instance.reviewEdits();doc.ids.confirmProposal.checked=true;await instance.applyProposal();assert.equal(instance.state.project.revision,1);assert.equal(instance.state.pending.size,1);assert.equal(instance.state.proposal.proposal_id,PROPOSAL);assert.match(doc.ids.notice.textContent,/版本冲突/);});
test('history is read only and returning to current version restores write controls',async()=>{const {instance,doc}=await app(async url=>response({project:project(url.includes('version=1')?1:3)}));instance.acceptProject(project(3));await instance.openProject(PID,1);assert.equal(instance.state.historical,true);assert.equal(doc.ids.reviewEdits.disabled,true);assert.equal(doc.ids.confirmLedger.disabled,true);assert.equal(doc.ids.exportProject.disabled,true);instance.edit('R00001','quantity','15');assert.equal(instance.state.pending.size,0);await instance.openProject(PID);assert.equal(instance.state.historical,false);assert.equal(instance.state.project.revision,3);assert.equal(doc.ids.undoProject.disabled,false);});
test('source evidence uses safe text and exact original cells; untrusted remote URLs are ignored',async()=>{const {instance,doc}=await app();const p=project();p.document.rows[0].evidence.quantity.raw='<img src=x onerror=alert(1)>';p.document.source.filename='<script>bad</script>.xlsx';instance.acceptProject(p);instance.showSource('R00001','quantity');assert.match(text(doc.ids.sourceFacts),/装箱单 · C5/);assert.match(text(doc.ids.sourceFacts),/<img src=x onerror=alert\(1\)>/);assert.equal(doc.ids.sourceDownload.href,`/api/logistics/projects/${PID}/source`);assert.equal(doc.ids.sourceFacts.children.some(n=>n.tagName==='img'),false);const {sourceLocation}=await modulePromise;assert.equal(sourceLocation({sheet:'Sheet',row:3,column:28}),'Sheet · AB3');});
test('PDF page bounding box includes coordinate system without pretending to map raster pixels',async()=>{const {instance,doc}=await app();const p=project();p.document.source.filename='original.pdf';p.document.rows[0].evidence.quantity.source={page:2,bbox:[1,2,30,40],coordinate_system:'pdf_points'};instance.acceptProject(p);instance.showSource('R00001','quantity');assert.equal(doc.ids.sourcePreview.children[0].src,`/api/logistics/projects/${PID}/source#page=2`);assert.match(text(doc.ids.sourceFacts),/pdf_points/);assert.match(text(doc.ids.sourceFacts),/框 \[1, 2, 30, 40\]/);});
test('different quantity units have separate totals and never display a fabricated combined piece count',async()=>{const {instance,doc}=await app();const p=project();p.summary.quantities_by_unit={PCS:10,米:25,UNSPECIFIED:4};p.summary.totals.quantity='UNSPECIFIED';instance.acceptProject(p);const out=text(doc.ids.totals);assert.match(out,/PCS/);assert.match(out,/米/);assert.match(out,/单位待确认/);assert.doesNotMatch(out,/39|件（按原始口径）/);});
test('calculation requires the current ledger confirmation and exact typed signoff',async()=>{let calls=0;const {instance,doc}=await app(async()=>{calls++;return response(pack());});await instance.calculate();assert.equal(calls,0);instance.acceptProject(project(1,{confirmed:true}));await instance.calculate();assert.equal(calls,0);doc.ids.confirmation.value=SIGNOFF;await instance.calculate();assert.equal(calls,1);assert.equal(instance.currentPacking(),true);});
test('failed computation retains the previous result but labels it as previous, and stale revision output is rejected',async()=>{let count=0;const {instance,doc}=await app(async()=>++count===1?response(pack()):count===2?response({detail:'缺少明确尺寸'},422):response(pack({revision:99})));instance.acceptProject(project(1,{confirmed:true}));doc.ids.confirmation.value=SIGNOFF;await instance.calculate();const old=copy(instance.state.packing);await instance.calculate();assert.deepEqual(instance.state.packing,old);assert.match(doc.ids.calculationState.textContent,/本次计算未完成/);assert.match(text(doc.ids.packingResult),/上次成功记录/);await instance.calculate();assert.deepEqual(instance.state.packing,old);assert.match(doc.ids.notice.textContent,/版本或模式不一致/);});
test('can_fit false is not presented as a successful calculation and keeps explicit failure details',async()=>{const {instance,doc}=await app(async()=>response(pack({ok:false,result:{ok:false,can_fit:false,needs_human:[{row_id:'R00001',message:'尺寸待确认'}]}})));instance.acceptProject(project(1,{confirmed:true}));doc.ids.confirmation.value=SIGNOFF;await instance.calculate();assert.equal(instance.state.packing,null);assert.match(doc.ids.notice.textContent,/未生成/);assert.match(text(doc.ids.packingResult),/尺寸待确认/);assert.match(doc.ids.calculationState.textContent,/未完成/);});
test('cancelled computation cannot publish late success and new options invalidate previous result',async()=>{const old=deferred();let count=0;const {instance,doc}=await app(url=>url.endsWith('/pack')?(++count===1?Promise.resolve(response(pack())):old.promise):Promise.resolve(response({ok:true})));instance.acceptProject(project(1,{confirmed:true}));doc.ids.confirmation.value=SIGNOFF;await instance.calculate();doc.ids.containerType.value='40HQ';await doc.ids.containerType.emit('change');assert.equal(instance.currentPacking(),false);assert.match(text(doc.ids.packingResult),/当前台账、模式或柜型选项已改变/);const calculating=instance.calculate();await instance.cancel();old.resolve(response(pack()));await calculating;assert.equal(instance.state.packing.container,'20GP');assert.equal(instance.state.calculationAttempt.status,'cancelled');});
test('chat reads do not write ledger, and rejected tool actions are not reported as completed',async()=>{const {instance,doc}=await app(async()=>response({ok:false,reply:'只能引用已有行号。'}));await instance.chat('把 UNKNOWN 毛重改为 2');assert.equal(instance.state.project.revision,1);assert.equal(instance.state.proposal,null);assert.equal(instance.state.chats.at(-1).error,true);assert.match(doc.ids.notice.textContent,/未完成/);});
test('cancelled chat cannot bring a proposal into another project',async()=>{const old=deferred();const {instance}=await app(url=>url.endsWith('/conversation')?old.promise:Promise.resolve(response({ok:true})));const chatting=instance.chat('把 R00001 件数改为 12');await instance.cancel();instance.acceptProject(project(1,{id:OTHER}));old.resolve(response({ok:true,reply:'已建议',...proposal()}));await chatting;assert.equal(instance.state.project.id,OTHER);assert.equal(instance.state.proposal,null);assert.equal(instance.state.chats.length,0);});
test('linked proposals validate project and revision; undo proposals show the version difference',async()=>{let data=proposal({project:{id:OTHER,revision:1}});const {instance,doc}=await app(async()=>response(data));await instance.loadLinkedProposal(PROPOSAL);assert.equal(instance.state.proposal,null);assert.match(doc.ids.notice.textContent,/其他项目/);data=proposal({project:{id:PID,revision:2}});await instance.loadLinkedProposal(PROPOSAL);assert.equal(instance.state.proposal,null);data=proposal({action:'undo',proposal:null,changes:[{field:'revision',before:2,after:1}]});await instance.loadLinkedProposal(PROPOSAL);assert.equal(instance.state.proposal.action,'undo');assert.match(text(doc.ids.proposalRows),/项目 \/ 版本.*2.*1/);assert.match(doc.ids.proposalReason.textContent,/恢复/);});
test('export requires exact signoff and sends optimistic revision without a replacement ledger',async()=>{let body;const {instance,doc,downloads}=await app(async(url,init)=>{body=JSON.parse(init.body);return new Response('csv',{headers:{'Content-Disposition':'attachment; filename="ledger.xlsx"'}});});await instance.exportProject();assert.equal(downloads.length,0);doc.ids.confirmation.value=SIGNOFF;await instance.exportProject();assert.equal(downloads.length,1);assert.deepEqual(body,{expected_revision:1,format:'xlsx',confirmation:SIGNOFF});assert.equal(downloads[0].name,'ledger.xlsx');});
test('cancel while an export blob is arriving prevents a late download',async()=>{const blob=deferred();const {instance,doc,downloads}=await app(async url=>url.endsWith('/export')?{ok:true,status:200,headers:new Headers(),blob:()=>blob.promise}:response({ok:true}));doc.ids.confirmation.value=SIGNOFF;const exporting=instance.exportProject();await new Promise(r=>setImmediate(r));await instance.cancel();blob.resolve(new Blob(['late']));await exporting;assert.equal(downloads.length,0);});
test('imported project resets typed signoff and does not reuse old packing result',async()=>{const {instance,doc}=await app(async url=>url.endsWith('/import')?response({project:project(1,{id:OTHER,confirmed:false})}):response({projects:[]}));instance.acceptProject(project(1,{confirmed:true}));instance.state.packing={projectId:PID,revision:1,mode:'packaged',container:'20GP',max:1,payload:pack()};doc.ids.confirmation.value=SIGNOFF;doc.ids.importFile.files=[new File(['zip'],'handoff.zip')];await instance.importProject();assert.equal(instance.state.project.id,OTHER);assert.equal(instance.state.packing,null);assert.equal(doc.ids.confirmation.value,'');assert.equal(doc.ids.calculate.disabled,true);});
test('capability reports environment found separately from actual OCR model readiness',async()=>{const {instance,doc}=await app(async url=>response(url.endsWith('/capabilities')?{limits:{source_bytes:8388608},ocr:{engine:'PP-StructureV3',environment_found:true,ready:false,available:false,reason:'模型未就绪。'}}:{projects:[]}));await instance.initialize();assert.match(doc.ids.capabilities.textContent,/环境已安装，模型尚未就绪/);assert.doesNotMatch(doc.ids.capabilities.textContent,/模型已就绪/);});
test('large ledgers paginate without losing pending edits across pages',async()=>{const {instance,doc}=await app();const p=project();p.document.rows=Array.from({length:61},(_,i)=>({...copy(p.document.rows[0]),id:`R${String(i+1).padStart(5,'0')}`}));instance.acceptProject(p);assert.equal(doc.ids.ledgerRows.children.length,30);instance.edit('R00001','quantity','12');await doc.ids.nextPage.click();assert.equal(doc.ids.ledgerRows.children.length,30);await doc.ids.previousPage.click();assert.equal(field(doc,'R00001','quantity').value,'12');assert.equal(instance.state.pending.size,1);});
test('late capability initialization cannot override a newly selected draft with the startup project URL',async()=>{const caps=deferred(),calls=[];const {instance,win}=await app(async url=>{calls.push(url);if(url.endsWith('/capabilities'))return caps.promise;if(url.endsWith('/example'))return response(draft());return response({projects:[]});},{saved:false});win.location.search=`?project_id=${PID}`;const initial=instance.initialize();await instance.example();caps.resolve(response({ocr:{available:false}}));await initial;assert.equal(instance.state.project,null);assert.equal(instance.state.draft.document_id,DID);assert.equal(calls.includes(`/api/logistics/projects/${PID}`),false);});
test('an incomplete success-shaped solver response is not accepted without exact can_fit and result ok',async()=>{const {instance,doc}=await app(async()=>response(pack({result:{ok:true,containers_used:1}})));instance.acceptProject(project(1,{confirmed:true}));doc.ids.confirmation.value=SIGNOFF;await instance.calculate();assert.equal(instance.state.packing,null);assert.match(doc.ids.notice.textContent,/未生成可用/);});
test('comparison selector excludes current project and submits only explicit project IDs and revision',async()=>{let body;const comparison={rows:[{material_id:'MAT-1',status:'different',current_row:'R00001',comparison_row:'R001',differences:{quantity:{current:10,comparison:20}}},{material_id:'DUP',status:'ambiguous_duplicate'}],unmatched_current:['R2'],unmatched_comparison:[],note:'仅按明确且唯一的材料编号对照原值，不按名称猜匹配。'};const {instance,doc}=await app(async(url,init)=>{if(url.endsWith('/projects'))return response({projects:[project(),project(3,{id:OTHER,name:'对照项目'})]});body=JSON.parse(init.body);return response({ok:true,comparison_revision:4,comparison});});await instance.refreshProjects();assert.equal(doc.ids.compareProjects.children.some(n=>n.value===PID),false);doc.ids.compareProjects.value=OTHER;await doc.ids.compareProjects.emit('change');await doc.ids.compareProject.click();assert.equal(body.compare_project_id,OTHER);assert.equal(body.expected_revision,1);assert.equal(instance.state.project.revision,1);assert.match(text(doc.ids.comparisonResult),/当前项目版本 1.*对照项目 · 版本 4/);assert.match(text(doc.ids.comparisonResult),/10.*20/);assert.match(text(doc.ids.comparisonResult),/编号重复，未自动匹配/);assert.match(text(doc.ids.comparisonResult),/当前台账无明确材料编号：R2/);instance.edit('R00001','quantity','30');assert.match(text(doc.ids.comparisonResult),/上次对照记录/);});
test('pending edits block comparison without sending a request',async()=>{let calls=0;const {instance,doc}=await app(async()=>{calls++;return response({});});instance.state.recentProjects=[project(2,{id:OTHER})];doc.ids.compareProjects.value=OTHER;instance.edit('R00001','quantity','12');await instance.compareProject();assert.equal(calls,0);assert.equal(instance.state.comparison,null);});
test('cancelled comparison cannot publish a report in a newly opened project',async()=>{const old=deferred();const {instance,doc}=await app(url=>url.endsWith('/conversation')?old.promise:Promise.resolve(response({ok:true})));instance.state.recentProjects=[project(2,{id:OTHER})];doc.ids.compareProjects.value=OTHER;const comparing=instance.compareProject();await instance.cancel();instance.acceptProject(project(1,{id:OTHER}));old.resolve(response({ok:true,comparison_revision:2,comparison:{rows:[]}}));await comparing;assert.equal(instance.state.project.id,OTHER);assert.equal(instance.state.comparison,null);});
test('container, box and packaging type remain independent fields with neutral packaging counts',async()=>{const {instance,doc}=await app();const p=project();Object.assign(p.document.rows[0],{container_id:'DEMO-CONTAINER',package_id:'BOX-1',package_type:'木箱'});instance.acceptProject(p);assert.equal(field(doc,'R00001','container_id').value,'DEMO-CONTAINER');assert.equal(field(doc,'R00001','package_id').value,'BOX-1');assert.equal(field(doc,'R00001','package_type').value,'木箱');assert.match(text(doc.ids.ledgerHead),/集装箱号.*箱号.*包装类型/);assert.match(text(doc.ids.totals),/包装数.*包装单位/);assert.doesNotMatch(text(doc.ids.totals),/箱数/);instance.edit('R00001','package_type','铁框');assert.equal(instance.state.pending.get('R00001:package_type').raw,'铁框');assert.equal(instance.state.project.document.rows[0].container_id,'DEMO-CONTAINER');});
test('shared merged evidence keeps one value, disables each grouped field and shows original range and coordinates',async()=>{const {instance,doc}=await app();const p=project(),first=p.document.rows[0],second={...copy(first),id:'R00002',material_id:'MAT-2',gross_kg:'UNSPECIFIED'};p.document.rows.push(second);const group={id:'synthetic-weight-group',row_ids:['R00001','R00002'],anchor_row_id:'R00001',source:{page:2,bbox:[10,20,50,80],coordinate_system:'pdf_points'}};for(const row of p.document.rows)row.evidence.gross_kg={raw:row.id==='R00001'?'120':'',source:copy(group.source),group:copy(group)};instance.acceptProject(p);assert.equal(field(doc,'R00001','gross_kg').value,'120');assert.equal(field(doc,'R00002','gross_kg').value,'');assert.equal(field(doc,'R00002','gross_kg').placeholder,'共享合并值');for(const row of p.document.rows){const node=field(doc,row.id,'gross_kg');assert.equal(node.disabled,true);assert.equal(node.readOnly,true);assert.equal(node.getAttribute('aria-readonly'),'true');node.value='121';await node.emit('input');assert.equal(instance.state.pending.size,0);}assert.equal(instance.state.project.document.rows[1].gross_kg,'UNSPECIFIED');assert.match(text(doc.ids.ledgerRows),/共享合并值 · 来源/);instance.showSource('R00002','gross_kg');const details=text(doc.ids.sourceFacts);assert.match(details,/共享合并值，未分摊到本行/);assert.match(details,/R00001、R00002/);assert.match(details,/唯一记值行.*R00001/);assert.match(details,/第 2 页 · 框 \[10, 20, 50, 80\]/);assert.match(details,/pdf_points/);assert.match(details,/只记录一次|仅记录一次/);assert.match(details,/共享原文  120/);assert.match(details,/共享值（不分摊）  120/);assert.equal(instance.state.project.document.rows[1].evidence.gross_kg.raw,'');assert.equal(instance.state.project.document.rows[1].gross_kg,'UNSPECIFIED');});
test('shared fields remain read only after unrelated edits and clearing drafts',async()=>{const {instance,doc}=await app();const p=project();p.document.rows[0].evidence.net_kg={raw:'100',source:{sheet:'Demo',row:3,column:4},group:{id:'synthetic-net',row_ids:['R00001'],anchor_row_id:'R00001',source:{sheet:'Demo',row:3,column:4}}};instance.acceptProject(p);instance.edit('R00001','quantity','12');assert.equal(field(doc,'R00001','net_kg').disabled,true);instance.discardEdits();assert.equal(field(doc,'R00001','net_kg').disabled,true);assert.equal(field(doc,'R00001','quantity').disabled,false);});
test('mixed-unit or unverifiable totals preserve the source declaration separately from unit totals',async()=>{const {instance,doc}=await app();const p=project();p.summary.quantities_by_unit={PCS:10,米:25};p.summary.totals.quantity='UNSPECIFIED';p.document.totals=[{values:{quantity:35,gross_kg:120},row_ids:['R00001'],source:{sheet:'Demo',row:8,column:3}}];p.audit.issues=[{severity:'warning',code:'mixed_quantity_units',message:'原件总计混合单位，不能直接相加。'}];instance.acceptProject(p);assert.equal(doc.ids.sourceTotals.hidden,false);assert.equal(doc.ids.sourceTotals.open,true);assert.match(text(doc.ids.sourceTotalsRows),/Demo · C8/);assert.match(text(doc.ids.sourceTotalsRows),/35（原表合计，单位与适用范围须核对）/);assert.match(text(doc.ids.totals),/10.*PCS.*25.*米/);assert.doesNotMatch(text(doc.ids.totals),/35/);});
test('missing or unrelated anchors leave shared source values unconfirmed',async()=>{const {instance,doc}=await app();const p=project();p.document.rows[0].gross_kg='UNSPECIFIED';p.document.rows[0].evidence.gross_kg={raw:'',source:{},group:{id:'synthetic-shared',row_ids:['R00001','R00002'],anchor_row_id:'R00002',source:{}}};instance.acceptProject(p);instance.showSource('R00001','gross_kg');assert.match(text(doc.ids.sourceFacts),/共享原文  待确认/);assert.match(text(doc.ids.sourceFacts),/共享值（不分摊）  待确认/);const unrelated={...copy(p.document.rows[0]),id:'R00002',gross_kg:999};unrelated.evidence.gross_kg={raw:'999',source:{},group:{id:'different-group',anchor_row_id:'R00002',row_ids:['R00002'],source:{}}};p.document.rows.push(unrelated);instance.acceptProject(p);instance.showSource('R00001','gross_kg');assert.match(text(doc.ids.sourceFacts),/共享值（不分摊）  待确认/);assert.doesNotMatch(text(doc.ids.sourceFacts),/999/);assert.equal(instance.state.project.document.rows[0].gross_kg,'UNSPECIFIED');});
